### ISSUE TITLE
Enable full support for JDK8

### ISSUE THREAD

**Issue by jmehrens** [swiesend/secret-service#11]
The example source code fails to execute on JDK8 due to the following error:

Exception in thread "main" java.lang.NoSuchMethodError: java.nio.ByteBuffer.rewind()Ljava/nio/ByteBuffer;
	at org.freedesktop.secret.Secret.clear(Secret.java:166)
	at org.freedesktop.secret.Secret.toBytes(Secret.java:128)
	at org.freedesktop.secret.TransportEncryption.encrypt(TransportEncryption.java:109)
	at org.freedesktop.secret.simple.SimpleCollection.createItem(SimpleCollection.java:258)
	at org.freedesktop.secret.simple.SimpleCollection.createItem(SimpleCollection.java:291)

This is because maven has been setup using JDK9 or later and is using the source and target options instead of the newer 'release' flag. https://www.baeldung.com/maven-java-version

In JDK8 the ByteBuffer inherits a rewind method from Buffer:
https://docs.oracle.com/javase/8/docs/api/java/nio/ByteBuffer.html

In JDK9 a covariant return was added to ByteBuffer:
https://docs.oracle.com/javase/9/docs/api/java/nio/ByteBuffer.html#rewind--

**Comment by swiesend** [comment]
Hey @jmehrens,

thank you for pointing this out. The current [1.0.0-SNAPSHOT](https://oss.sonatype.org/content/repositories/snapshots/de/swiesend/secret-service/1.0.0-SNAPSHOT/) of the `1.0.0` branch is now using the `release` flag.

```xml
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.release>8</maven.compiler.release>
    </properties>

    <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.0</version>
                <configuration>
                    <release>8</release>
                </configuration>
            </plugin>
    </plugins>
```

Please tell me if this fixes the issue.

**Comment by jmehrens** [comment]
@swiesend This is working.  I verified that using "<dependency><groupId>de.swiesend</groupId><artifactId>secret-service</artifactId><version>1.0.0-RC.3</version></dependency>" fails with the error in the ticket description.  I then downloaded the secret-service-1.0.0-20200412.153343-2.jar. I then modified the pom (in the not preferred way) by doing "<dependency><groupId>de.swiesend</groupId><artifactId>secret-service</artifactId><scope>system</scope><version>1.0.0-20200412.153343-2</version><systemPath>/home/jmehrens/Downloads/secret-service-1.0.0-20200412.153343-2.jar</systemPath></dependency>" and verified that the exact same test program completed without the java.lang.NoSuchMethodError.
