### ISSUE TITLE
Please update to dbus-java 3.2.3

### ISSUE THREAD

**Issue by purejava** [swiesend/secret-service#13]
dbus-java 3.2.3 will be released shortly.
It contains a fix (dbus-java #110), that is essential for kdewallet to work correctly.

As Cryptomator includes secret-service and probably will include kdewallet as well, they need to depend on the same dbus-java version.

Thanks.

**Comment by swiesend** [comment]
Version `1.0.1` with the updated `dbus-java` version is released.

But I will also provide a non breaking version with hopefully enhanced signal handling.

**Comment by swiesend** [comment]
Now there is also `1.1.0` with improved signal handling, which _may_ solves the freeze issue (https://github.com/cryptomator/cryptomator/issues/1268), too.
