### ISSUE TITLE
Does Lock / Unlock method do anything for a non-default SimpleCollection? 

### ISSUE THREAD

**Issue by shahzaibj** [swiesend/secret-service#28]
I'm creating an instance of a `SimpleCollection` object for a non-default collection as follows:

```java
SimpleCollection collection = new SimpleCollection("My Collection", "<my-secret>")
```

It seems that calling the `lock` and `unlock` methods on this instance don't do anything and the collection is effectively always unlocked as I am always able to create items and get items from this collection. Is this expected? What should be the expected behavior after calling `lock` on such a collection?

**Comment by swiesend** [comment]
This is a not so well documented feature of my library:

Named collections can be unlocked without a prompt as they make use of the of the `org.gnome.keyring.InternalUnsupportedGuiltRiddenInterface.unlockWithMasterPassword(DBusPath collection, Secret master)` API.

If a collection secret (_master password_) is present, then it automatically gets used to unlock the collection if necessary, but does not lock the collection again. This might be unwanted behavior, but can't be configured for now. The only way to ensure that a collection stays `Locked` is to call `SimpleCollection.lock()` after each interaction with the collection.

One can provide an empty collection secret (`null`) for named `SimpleCollection`s, which results in the following behaviors:

<table>
<tr><td></td><td>new collection</td><td>locked</td><td>unlocked</td></tr>
<tr><td>default collection: `SimpleCollection()`</td><td>???</td><td>prompts for the password the first time only</td><td>no prompt</td></tr>
<tr><td>named collection with secret: `SimpleCollection("name", "secret")` </td><td>no prompt</td><td>no prompt</td><td>no prompt</td></tr>
<tr><td>named collection, no secret: `SimpleCollection("name", null)`  </td><td><img src="https://user-images.githubusercontent.com/3512490/123554458-5e21ef00-d780-11eb-8f85-8d22ce27bdb7.png"></td><td><img src="https://user-images.githubusercontent.com/3512490/123554592-fc15b980-d780-11eb-916a-a86fed1ab773.png"> or no prompt.</td><td>no prompt</td></tr>
</table>

Ticking _Automatically unlock this keyring whenever I'm logged in_ results into an extra entry (I call it a magic entry, as it does not seem to appear anymore in seahorse) in the default collection, which stores the collection secret. So GNOME searches for such entry (with a key value pair like: `keyring: LOCAL:/keyrings/test.keyring`) in the default collection and if there is non present will prompt for the password.

You can check that the collection actually gets locked with:
- `SimpleCollection.isLocked()`, which is a remote dbus call
- seahorse
- or via `dbus-send`

**Comment by shahzaibj** [comment]
@swiesend Thanks, this is helpful. I was trying it out and I actually didn't see any checkbox for _Automatically unlock this keyring whenever I'm logged in_. Is there some specific thing I need to do to get that checkbox? (I was trying it out on WSL and not sure if that is the reason...I will try on a real system later as well)
