### ISSUE TITLE
Do we have some benchmarks available for this library?

### ISSUE THREAD

**Issue by shahzaibj** [swiesend/secret-service#29]
Using an unlocked default collection...I'm seeing a single write take about 32 milliseconds on average and a single read take about 6.5 milliseconds on average.

Comparing this with KDE Wallet using the [JAVA KDE Wallet library](https://github.com/purejava/kdewallet), I see the following on KDE Wallet:

With KWallet, I see a single write take about 0.675 milliseconds on average and a single read take about 0.489 seconds on average.

I initially thought it was due to DBus, however, KWallet also operates over DBus...so not sure why this library takes so much time.

**Comment by shahzaibj** [comment]
and the time really goes up if the collection is locked...in the case of Locked collection (when the password is supplied..and it is doing unlock with master password i.e. no prompt shown), I see write take about 100 milliseconds and read take about 10 milliseconds

**Comment by purejava** [comment]
> 
> 
> and the time really goes up in the case of a named collection with secret supplied, I see write take about 100 milliseconds and read take about 10 milliseconds. I believe in this case, your library is locking the collection after every access and unlocking before every access (at least that's what I understood per this: #28).
> 
> In either case, it seems very slow.

Slow compared to what? Slow compared to your expectations? Well, feel free to write a faster software.

Comparing secret-service to kdewallet is like comparing chalk to cheese. Both are Java adapters, but to totally different backends being used.

If you are interested in what secret-service is doing, you can check out for yourself. You can either use `dbus-monitor` or trace system calls and signals the D-Bus daemon is sending to the Linux kernel with `strace`.

**Comment by swiesend** [comment]
@shahzaibj there is maybe potential to improve things, but I honestly did not focus on performance. It would be nice to profile the library and get an idea where its taking its time. But I guess, that most of the time will be spent in the backend.

I think @purejava is right, although a bit too harsh with his words. If you like to improve things you are very welcome to do so!

I didn't do a lot of profiling in java, so i can't recommend any IDE or library. Please, let me know, if you have results and know about concert offending behavior of a function. I am willing to improve things and there is still the plan to redesign the library API for a 2.0.0 version with better API design.

I noticed that the Secret Service backend emits a lot of signals, when closing or opening a collection, as if effectively emits a signal for each entry in the collection and for the changed state of the collection itself. Maybe it is possible to suppress this behavior and get some speedup, but that would be deep in the weeds of `gnome-keyring`.

**Comment by shahzaibj** [comment]
Thanks @purejava and @swiesend for the responses. Sounds like the slow writes have to do with the inherent nature of the `gnome-keyring` backend than it has to do with this library. I think that makes sense. I'll go ahead and close this issue. Thanks folks!
