### ISSUE TITLE
Update to `dbus-java` 4.x

### ISSUE THREAD

**Issue by overheadhunter** [swiesend/secret-service#31]
This is a feature request that will not be downwards compatible and may require a new major version:

Could you please update `dbus-java` to version 4? It got modularized and offers a variety of transport implementations, including `dbus-java-transport-native-unixsocket`, which relies on Java's native unix sockets, so we could get rid of the dependency to the whole JNR ecosystem.

This requires to bump the JDK to 17 (technically 16, but I guess LTS makes more sense). On the long run, this is the most important step to make this library work with Java's module system.

**Comment by swiesend** [comment]
I have seen it. Last time I checked there was no jar on maven yet, as the 4.x version was just released. I try it for this week. Will also update the intergrations-linux.

**Comment by swiesend** [comment]
I found some time to integrate `dbus-java` `4.x.x`. I am planning to release it together with my `2.x.x` API, that will provide am FP friendly API, as you suggested in: https://github.com/swiesend/secret-service/issues/7

I want to release my `2.0.0`, when `dbus-java` `4.1.x` will be available.

https://github.com/swiesend/secret-service/tree/develop-2.x.x

**Comment by overheadhunter** [comment]
This may be a little off topic but since you mentioned working on a new major version (and probably don't want to have further breaking changes after releasing it): Please consider using a package namespace that you have sole control over, as `org.gnome.*` etc will lead to split packages in the post-Java-8 modular world.

**Comment by brett-smith** [comment]
I've also been waiting on `dbus-java` `4.1.x` for other purposes, as well as being a consumer of this library (via https://github.com/javakeyring/java-keyring). So just thought I'd point out 4.1.0 has now been released :)

**Comment by swiesend** [comment]
> So just thought I'd point out 4.1.0 has now been released :)

Thanks @brett-smith! Currently I am on vaccation without my laptop. I am happy to use it when I am back in about two weeks.

**Comment by overheadhunter** [comment]
Since the jnr-based unix sockets implementation might fail in downstream projects, may I ask for our users, if there is any progress with this?

**Comment by swiesend** [comment]
@overheadhunter there is some progress, but its not pushed as it is not finished. Recently my father died and there are too many things going on right now. I try to find some spare time to get if off the table, but that probably need some more weeks. Bit its not forgotten.

**Comment by overheadhunter** [comment]
So sorry to hear that! Trust me, I know how this can derail one's life from one day to the other.

Don't feel pushed, I was just curious what is the status of this issue.

**Comment by infeo** [comment]
This issue is completed with the release of https://github.com/swiesend/secret-service/tree/v1.8.0-jdk17.
