### ISSUE TITLE
Working with other secret service implementations

### ISSUE THREAD

**Issue by shocklateboy92** [swiesend/secret-service#34]
The [Secret Service API 0.2](https://specifications.freedesktop.org/secret-service/0.2) as been a published standard for quite some time and is now implemented by other services including:
- [KeepassXC](https://avaldes.co/2020/01/28/secret-service-keepassxc.html)
- KWallet ([as of version 5.97](https://invent.kde.org/frameworks/kwallet/-/merge_requests/11)

However, if something tries to use `SimpleCollection` with one of those instead of gnome-keyring, it [just crashes](https://github.com/swiesend/secret-service/blob/46a49680fdabfa1998ad9b76a5dafca43f2d2e4b/src/main/java/org/freedesktop/secret/simple/SimpleCollection.java#L248) with:
```
IOException(""The secret service is not available.")
```
because the [org.gnome.keyring](https://github.com/swiesend/secret-service/blob/46a49680fdabfa1998ad9b76a5dafca43f2d2e4b/src/main/java/org/freedesktop/secret/simple/SimpleCollection.java#L182) dbus service is not available.

Is it possible to defer that check?
To only crash if someone tries to use a gnome-specific feature?

**Comment by shocklateboy92** [comment]
It looks like you'd just need to move that check into `InternalUnsupportedGuiltRiddenInterface.java`.

@swiesend : If I create a PR to make that change, will you accept it?

**Comment by purejava** [comment]
What exactly are you trying to achieve? 🙂

`SimpleCollection` was designed to work with gnome keyring and therefore needs this check.

KeePassXC does have a secret service feature, that attaches KeePassXC with the secret service API on your linux machine and allows applications to store passwords in KeePassXC via secret service instead of the gnome keyring, as secret service would normally do.

KeePassXC launches it's own daemon called "keepassxc" that provides it's own secret service interfaces, that is the middle layer between any application using a password backend and the password backend itself. KeePassXC's own secret service interfaces differ massively from the ones, gnome keyring does provide.

`SimpleCollection` does use the secret service API provided by gnome keyring.

**Comment by swiesend** [comment]
As @purejava pointed out: only skipping the check leads to other problems, as both dbus services (`secret-service` and `gnome-keyring`) are tightly integrated in the current implementation (see: [`InternalUnsupportedGuiltRiddenInterface`](https://github.com/swiesend/secret-service/blob/46a49680fdabfa1998ad9b76a5dafca43f2d2e4b/src/main/java/org/gnome/keyring/InternalUnsupportedGuiltRiddenInterface.java)). I think it would be possible to make it work with some refactoring, but currently I do not find the time for that. Although it would be a nice to have for the `2.x.x` branch. @shocklateboy92 you are more than welcome to make it happen.

Depending on what you need and want to achieve I think you are better off with @purejava's [`keepassxc-proxy-access`](https://github.com/purejava/keepassxc-proxy-access) and providing a small implementation of your own like https://github.com/purejava/keepassxc-cryptomator/blob/develop/src/main/java/org/purejava/integrations/keychain/KeePassXCAccess.java. Is that right @purejava?

**Comment by shocklateboy92** [comment]
Hi @purejava, @swiesend, thank you for your responses!

> What exactly are you trying to achieve? slightly_smiling_face

In short: to get rid of gnome-keyring from my machine :slightly_smiling_face: 

Since kwallet started implementing `org.freedesktop.secrets` interface, I've gotten pretty close - almost every app that required gnome-keyring now works with kwallet.
The holdout is Microsoft Identity Broker, which is required for corporate device enrollment/management. It crashes on startup if gnome-keyring is not running because it uses this library for credential storage.

Since I work for the company, I'm working on reaching out to the teams that own it to let me make a patch. However, when I get there I think a small patch to update the version of library they're already using would be an easier sell than building a new abstraction layer between 2 libraries :smirk: 

However, if you think messing with [InternalUnsupportedGuiltRiddenInterface](https://github.com/swiesend/secret-service/blob/46a49680fdabfa1998ad9b76a5dafca43f2d2e4b/src/main/java/org/gnome/keyring/InternalUnsupportedGuiltRiddenInterface.java) is a _much_ bigger task than I seem to think it is, then please let me know.

Also do let me know if you think there's a better way of achieving my goal of using kdewallet for everything.

PS: I don't really use keepassxc, I just brought it up because this change might be useful for people that do. :smile_cat:

**Comment by purejava** [comment]
> Also do let me know if you think there's a better way of achieving my goal of using kdewallet for everything.
> 
There is [`kdewallet`](https://github.com/purejava/kdewallet), which does not implement the Secret Service API, but accesses KWallet over it's D-Bus interfaces.
