### ISSUE TITLE
`ExceptionInInitializerError` thrown when calling SimpleCollection.isAvailable()

### ISSUE THREAD

**Issue by infeo** [swiesend/secret-service#47]
When calling `SimpleCollections::isAvailable`, there still can be an `ExceptionInInitailzerError` thrown.
```
Exception org.freedesktop.dbus.exceptions.AddressResolvingException: Cannot Resolve Session Bus Address: MachineId file can not be found [in thread "JavaFX Application Thread"]
```

This is related to the static init of the DBusConnection with the `getConnection()`method:
https://github.com/swiesend/secret-service/blob/d08ec918e6153bd689f244b107dbaeb25d38624a/src/main/java/de/swiesend/secretservice/simple/SimpleCollection.java#L133-L149

The thrown exceptions [`AddressResolvingException`](https://github.com/hypfvieh/dbus-java/blob/master/dbus-java-core/src/main/java/org/freedesktop/dbus/exceptions/AddressResolvingException.java) extends not DBusException, but the DBusExecutionException. Unfortunately, I don't know Linux systems good enough to evaluate if the machine-id file must always be readable (see above), but a defensive programming is always benefical.

See also https://github.com/cryptomator/cryptomator/issues/3279.

**Comment by swiesend** [comment]
@infeo thank you for pointing this out. The `DBusExecutionException` is handled now: https://github.com/swiesend/secret-service/blob/c0406b0579852252b38448973774fa49cb78f077/src/main/java/de/swiesend/secretservice/simple/SimpleCollection.java#L142

New release: `2.0.1-alpha`
