### ISSUE TITLE
slf4j-simple is in compile-scope

### ISSUE THREAD

**Issue by overheadhunter** [swiesend/secret-service#5]
... which leads to conflicts when using this library in any project using a different logger. Use `slf4j-api` instead and add `slf4j-simple` to test-scope.

**Comment by swiesend** [comment]
Good point, but in which scope should the `slf4j-api` be: `compile` or `runtime`?

**Comment by swiesend** [comment]
As mentioned [here](https://dzone.com/articles/adding-slf4j-your-maven) I've put slf4j-api into the `compile` (default) scope and `slf4j-simple` into `test` scope.

I published the change as [1.0.0-RC.2](https://oss.sonatype.org/content/groups/staging/de/swiesend/secret-service/1.0.0-RC.2/)
